// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cpjwpebmojcdrcvkfupc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNwandwZWJtb2pjZHJjdmtmdXBjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MjIzNTgsImV4cCI6MjA2NTQ5ODM1OH0.2fNbsNyRUhYqfTFynPE9se-7oYYnHrrslja_ZAQ1l8E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);